let items = [{
    img: 'assets/collection/pic_white.jpg',
    title: 'Chuck Taylor All Star Classic Low-Top',
    color: 'Белый',
    onPage: 'main',
    span: 'spanPicTwo',
    mainPic: 'mainColorPic',
    numberColors: 3,
    id: "whiteBtnTwo",
    price: 230 },
{
        img: 'assets/collection/2pic_2.jpg',
        title: 'Chuck Taylor All Star Classic Low-Top',
        color: 'Черный',
        numberColors: 3,
        id: "blackBtnTwo",
        price: 230},
{
        img: 'assets/collection/m9696_1.jpg',
        title: 'Chuck Taylor All Star Classic Low-Top',
        color: 'Красный',
        numberColors: 3,
        id: "redBtnTwo",
        price: 230},
{
        img: 'assets/collection/m7650_1.jpg',
        title: 'Chuck Taylor All Star Classic High-Top',
        color: 'Белый',
        onPage: 'main',
        span: 'spanPicTaylorHigh',
        mainPic: 'mainColorPicTaylorHigh',
        numberColors: 4,
        id: "whiteBtnOne",
        price: 230},
{
        img: 'assets/collection/1pic_black.jpg',
        title: 'Chuck Taylor All Star Classic High-Top',
        color: 'Черный',
        numberColors: 4,
        id: "blackBtnOne",
        price: 230},
{
        img: 'assets/collection/1pic_blue.jpg',
        title: 'Chuck Taylor All Star Classic High-Top',
        color: 'Синий',
        numberColors: 4,
        id: "blueBtnOne",
        price: 230},
{
        img: 'assets/collection/1pic_red.jpg',
        title: 'Chuck Taylor All Star Classic High-Top',
        color: 'Красный',
        numberColors: 4,
        id: "redBtnOne",
        price: 230},
    {
            img: 'assets/collection/162053_1.jpg',
            title: 'Chuck 70 Classic High-Top',
            color: 'Белый',
            onPage: 'main',
            span: 'spanPicChuckHigh',
            mainPic: 'mainColorPicChuckHigh',
            numberColors: 2,
            id: "whiteBtnThree",
            price: 300},
    {
            img: 'assets/collection/3pic_black.jpg',
            title: 'Chuck 70 Classic High-Top',
            color: 'Черный',
            numberColors: 2,
            id: "blackBtnThree",
            price: 300},
    {
        img: 'assets/collection/162062_1.jpg',
        title: 'Chuck 70 Classic Low-Top',
        color: 'Белый',
        span: 'spanPicChuckLow',
        mainPic: 'mainColorPicChuckLow',
        onPage: 'main',
        numberColors: 2,
        id: "whiteBtnFour",
        price: 290},
    {
        img: 'assets/collection/4pic_black.jpg',
        title: 'Chuck 70 Classic Low-Top',
        color: 'Черный',
        numberColors: 2,
        id: "blackBtnFour",
        price: 290},
    {
            img: 'assets/collection/171492_1.jpg',
            title: 'Chuck Taylor All Star Renew Crater Knit',
            color: 'Бирюзовый',
            onPage: 'main',
            span: 'spanPicChuckRenew',
            mainPic: 'mainColorPicChuckRenew',
            numberColors: 1,
            id: "lightblueBtn",
            price: 380},
    {
        img: 'assets/collection/171486_1.jpg',
        title: 'Chuck 70 Renew Knit High Top',
        color: 'Черный',
        onPage: 'main',
        span: 'spanPicChuckKnit',
        mainPic: 'mainColorPicChuckKnit',
        numberColors: 1,
        id: "blackKnitBtn",
        price: 335},
{
    img: 'assets/collection/171487_1.jpg',
    title: 'Chuck 70 Renew Knit Low Top',
    color: 'Черный',
    onPage: 'main',
    span: 'spanPicChuckKnitLow',
    mainPic: 'mainColorPicChuckKnitLow',
    numberColors: 1,
    id: "blackKnitLowBtn",
    price: 320},
{
    img: 'assets/collection/171565_1.jpg',
    title: 'Chuck 70 Canvas Color Vintage High Top',
    color: 'Зеленый',
    onPage: 'main',
    span: 'spanPicChuckVintage',
    mainPic: 'mainColorPicVintage',
    numberColors: 2,
    id: "greenBtnCanvas",
    price: 300},
    {
        img: 'assets/collection/canvas_red.jpg',
        title: 'Chuck 70 Canvas Color Vintage High Top',
        color: 'Красный',
        numberColors: 2,
        id: "redBtnCanvas",
        price: 300},
    {
        img: 'assets/collection/canvaslow_red.jpg',
        title: 'Chuck 70 Canvas Color Vintage Low Top',
        color: 'Красный',
        onPage: 'main',
        span: 'spanPicChuckVintageCanvasLow',
        mainPic: 'mainColorPicVintageCanvasLow',
        numberColors: 1,
        id: "redBtnCanvasLow",
        price: 280},
        {
            img: 'assets/collection/170381_1.jpg',
            title: 'Chuck 70 Pixelated Digital Camo High Top',
            color: 'Мульти',
            onPage: 'main',
            numberColors: 1,
            span: 'spanPicChuckDigital',
            mainPic: 'mainColorPicDigital',
            id: "turquoiseBtn",
            price: 335},
        {
            img: 'assets/collection/170382_1.jpg',
            title: 'Chuck 70 Pixelated Digital Camo Low Top',
            color: 'Мульти',
            onPage: 'main',
            span: 'spanPicChuckDigitalLow',
            mainPic: 'mainColorPicDigitalLow',
            numberColors: 1,
            id: "grayBtn",
            price: 335},
            {
                img: 'assets/collection/171680_1.jpg',
                title: 'Chuck Taylor All Star Ultra Hybrid Game',
                color: 'Мульти',
                onPage: 'main',
                span: 'spanPicChuckUltra',
                mainPic: 'mainColorPicUltra',
                numberColors: 1,
                id: "blackBtnUltra",
                price: 250},
]